# This is the main configuration file of your Dancer app
# env-related settings should go to environments/$env.yml
# all the settings in this file will be loaded at Dancer's startup.

# Your application's name
appname: "myPKM"

# The default layout to use for your application (located in
# views/layouts/main.tt)
layout: "main"

# when the charset is set to UTF-8 Dancer will handle for you
# all the magic of encoding and decoding. You should not care
# about unicode within your app when this setting is set (recommended).
charset: "UTF-8"

# template engine
# simple: default and very basic template engine
# template_toolkit: TT

# template: "simple"

template: "template_toolkit"
engines:
  template_toolkit:
    encoding:  'utf8'
    start_tag: '<%'
    end_tag:   '%>'

plugins:
  DBIC:
    mypkm:
      schema_class: myPKM::Schema
      dsn: dbi:SQLite:dbname=/home/manu/projets/myPKM/archive.db
      options:
        sqlite_unicode: 1
  Lucy:
    index: /home/manu/.mypkm/lucy/
    polyanalyser:
      language: en
    schema:
      fields:
        - id
        - content
        - url
        - title
    create: 0

plack_middlewares:
  Debug:
    - panels
    -
      - Dancer::Routes
